namespace GestaoDespesas.Api.Models;

// Represents a single expense entry made by a user
public class Expense
{
    // Primary key, auto-generated by the database
    public int Id { get; set; }

    // Short description of the expense (e.g. "Groceries", "Uber ride")
    public string Description { get; set; } = string.Empty;

    // Monetary amount of the expense
    public decimal Amount { get; set; }

    // Date the expense occurred (not when it was recorded in the system)
    public DateTime Date { get; set; }

    // Foreign key: links this expense to a category (e.g. "Food")
    public int CategoryId { get; set; }

    // Navigation property: allows EF Core to load the related Category
    // when needed (e.g. Include(e => e.Category))
    public Category? Category { get; set; }

    // Foreign key: links this expense to the user who created it
    public string UserId { get; set; } = string.Empty;
}